version: '3.8'

services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - '4321:5432'
  node-server-app:
    depends_on:
      - db
    image: node-server:latest
    restart: always
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=root
      - DB_NAME=postgres
    ports:
      - '443:5000'
volumes:
  db:
    driver: local
