stages:          # List of stages for jobs, and their order of execution
  - build
#  - test
  - deploy


build-job:
  stage: build
  script:
    - docker compose -f web/dev_env/test/docker-compose.yaml down
    - docker compose -f web/dev_env/test/docker-compose.yaml build node-server-app-test
    - docker compose -f web/dev_env/test/docker-compose.yaml up --abort-on-container-exit
  tags:
    - nodejs-postgre-desktop

deploy-prod:
  stage: deploy
  only:
    - pre-prod
  script:
    - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
  environment: production
  tags:
    - nodejs-postgre-desktop